README.md
config.yaml.inc
federated_boto/cli.py
federated_boto/login.py
federated_boto/sts_conn.py

Removed Auth0 API and API identifier (audience) as it looks like Auth0 constructs
the audience value on it's own
Add error checking to response from AWS
Enable passing scope to login
Change scope to openid
Change login to return all tokens (instead of access_token) as we need id_token
Fix logging by creating root logger in cli
Add docs about config file contents

Remove audience

---

setup.py

Let's move to CHANGELOG.md after we have the first version
https://keepachangelog.com/en/0.3.0/#what-should-the-change-log-file-be-named

Get rid of HISTORY.md

---

cloudformation/functions/get_group_role_map.py
cloudformation/functions/get_security_audit_role_arns.py
cloudformation/functions/tests/test_get_secuity_audit_role_arns.py
cloudformation/tox.ini

* Run flake8 checks for lambda functions under Python 3 
* Rename pagination argument "credentials" to "client_args"
* Since the argument can be used for more than just credentials, rename it so that it's more clear how it can be used

Add get_security_audit_role_arns function

---

cloudformation/functions/build_group_role_map.py
cloudformation/functions/compare_group_arn_maps.py
cloudformation/functions/get_group_role_map.py
cloudformation/functions/get_security_audit_role_arns.py
cloudformation/functions/tests/test_build_group_role_map.py
cloudformation/functions/tests/test_compare_group_arn_maps.py

This fetches, stores and compares the group ARN map in S3
Also 
* Clarify optional arguments with type hints 
* Make flip_map generic to work with flipping maps either direction 
* Rename get_group_role_map to build_group_role_map

Add compare_group_arn_maps module

---

cloudformation/Makefile
cloudformation/functions/group_role_map_builder.py
cloudformation/group_role_map_builder.yaml
cloudformation/tox.ini

* Switch tox to py37 to match Lambda interpreter 
* Fix default s3 bucket name in Makefile 
* Remove default S3 bucket name
* Since S3 bucket names are a global namespace, there's little value in having a default
* Log new group role map if it changes 
* Set LogGroup retention time 
* Fix copy paste name mistake 
* Add Lambda function tag pointing to source code location 
* Clarify logging 
* Increase timeout for group role map builder 
* Accommodate security IAM roles which have been deleted
* In the case where an AWS account is closed and the CloudFormation stacks
within are not torn down, the cross account stack emissions DB will contain
IAM role ARNs which no longer exist. This logs that they don't work and skips them.

Accommodate security IAM roles which have been deleted

---

cloudformation/Makefile
cloudformation/deploy.sh
cloudformation/group_role_map_builder/group_role_map_builder.yaml
cloudformation/idtoken_for_roles/functions/idtoken_for_roles.py
cloudformation/idtoken_for_roles/idtoken_for_roles.yaml

* Add support for custom domain names
* Add API endpoint that returns AWS account ID alias map
* Removed code that enables API Gateway logging to CloudWatch as that should be managed by an account-wide template, not this specific service

 Add custom domain names, alias map endpoint

---

cloudformation/group_role_map_builder/functions/group_role_map_builder.py
cloudformation/group_role_map_builder/tests/policies/one_group_stringequals.json
cloudformation/tox.ini

* fix flake8 tox check so flake8 checks code
* resolve flake8 warnings
* add debug and error logging
Cause of the bug was that `any([[False],[False]])` is `True` not `False`

Fix bug with valid StringEquals conditions

---

cloudformation/Makefile
cloudformation/group_role_map_builder/functions/group_role_map_builder.py
cloudformation/group_role_map_builder/group_role_map_builder.yaml
cloudformation/group_role_map_builder/tests/policies/invalid_stringequals_multiple_groups_with_glob.json
cloudformation/group_role_map_builder/tests/policies/invalid_stringequals_one_group_with_glob.json
cloudformation/group_role_map_builder/tests/policies/invalid_stringequals_one_group_with_question_mark.json
cloudformation/group_role_map_builder/tests/policies/multiple_groups_stringlike.json
cloudformation/group_role_map_builder/tests/policies/no_conditions.json
cloudformation/group_role_map_builder/tests/policies/one_group_stringequals.json
cloudformation/group_role_map_builder/tests/policies/one_group_stringlike.json
cloudformation/group_role_map_builder/tests/policies/unknown_amr.json
cloudformation/group_role_map_builder/tests/policies/unknown_arn.json
cloudformation/group_role_map_builder/tests/policies/unsupported_too_many_conditions.json
cloudformation/group_role_map_builder/tests/test_compare_group_arn_maps.py
cloudformation/group_role_map_builder/tests/test_get_groups_from_policy.py
cloudformation/group_role_map_builder/tests/test_get_secuity_audit_role_arns.py
cloudformation/idtoken_for_roles/idtoken_for_roles.yaml
federated_aws_cli/cli.py
federated_aws_cli/login.py
federated_aws_cli/role_picker.py
federated_aws_cli/sts_conn.py
tests/test_federated_aws_cli.py

* Move login.configure to `__init__` and meet PEP008 needs
* Gracefully deal with cases where the STS call fails
* Pass in more prod and dev specific values
* Removes hardcoded defaults and passes those values in via the Makefile
* Improve tests
* Remove real values from tests and replace with example values
* Move configuration settings that exist as constants at the root
of the module to a set of DEFAULTS and a get_settings method to
fetch them. This enables overriding these settings in unit tests
as resolving the environment variables and the defaults happens
at invocation instead of at module import time.
* Add clarifying output text to test_get_groups_from_policy. This
was needed because the assertions and exception checks don't
reveal which policy is failing.

Allow for passing in prod and dev specific config values

---

federated_aws_cli/login.py

This fixes bugs introduced in https://github.com/mozilla-iam/federated-aws-cli/pull/85/commits/7a2be16daaecae23a3c39ebb8c1b32233bc8a4e7
which was squashed into f740aed6db53cecbb5c11d6459fa89068dbb4551
By recreating the changes that were lost from https://github.com/mozilla-iam/federated-aws-cli/pull/85/commits/043ab598cb65fcea4fd22177b5a200d03add77a7
That provide "Pass all query parameters through so that error messages are passed"
This is the second of two bugs introduced in that conflict solving merge commit, the other one fixed in https://github.com/mozilla-iam/federated-aws-cli/pull/85/commits/9fe74a1a35901bb49ebbf47ca3be85439227ace7

Fix bugs introduced during merge and conflict resolution

---

cloudformation/Makefile
cloudformation/deploy.sh
federated_aws_cli/listener.py
federated_aws_cli/static/index.html
federated_aws_cli/static/index.js
federated_aws_cli/sts_conn.py
tox.ini

* Try to provision a 12 hour session and fall back to 1 hour if that fails
* Clarify how the debug variable is set
* Fix the Makefile S3 bucket names
* Previously, the template files were being stored in the Auth0 asset bucket by mistake
* Set tox to set pytest to not capture logs/output from the tests and instead pass it through.
* This should make debugging easier

 Change template to support both mustache and handlebars 

---

federated_aws_cli/cli.py
federated_aws_cli/login.py

This has a default of the Mozilla federated RP. We should probably establish a more centralized method to enumerate defaults. When we do we can move this default there.
This also doesn't do anything for refreshing the CLI session.

Add support for redirecting to the web RP when the web session expires

---

CHANGELOG.md
mozilla_aws_cli/cli.py

Changed the precedence of the mozilla_aws_cli_config module such that if the
module is present it overrides settings in the ~/.maws/config file only for
settings that it asserts, leaving any additional settings set in the config
file intact

Change mozilla_aws_cli_config precedence

---

mozilla_aws_cli/cli.py
tests/test_federated_aws_cli.py

Fix CLI output, multiple configs, improve tests

---

README.md
mozilla_aws_cli/cache.py
mozilla_aws_cli/listener.py
mozilla_aws_cli/login.py
mozilla_aws_cli/static/index.js
mozilla_aws_cli/sts_conn.py
setup.py

Handle ExpiredTokenException correctly and restructure flow paths
* get_id_token was a method that did far more than getting an id token.
This change explodes the functionality in that method into multiple
methods.
* `get_id_token`
* `validate_id_token`
* `get_role_map`
* `exchange_token_for_credentials`
* `print_output`
* Add checking for when AWS responds with ExpiredTokenException and
initiate a new auth flow to fetch a new ID token.
* This would come into play when we have a cached ID token that is
older than the AWS undocumented max ID token validity of 1 day
* This means that listener.py can now initiate a redirect for the user
to start the auth flow over
* This includes a new `state` value called "restart_auth" that triggers
the redirect to the IdP to restart the auth flow
* Break …

Handle ExpiredTokenException correctly and restructure flow paths

---

mozilla_aws_cli/cache.py
mozilla_aws_cli/cli.py
mozilla_aws_cli/login.py

Add an option to set the profile name, both for shared/awscli output

---

README.md
cloudformation/Makefile
cloudformation/group_role_map_builder/functions/group_role_map_builder.py
cloudformation/group_role_map_builder/group_role_map_builder.yaml
cloudformation/idtoken_for_roles/functions/idtoken_for_roles.py
cloudformation/idtoken_for_roles/idtoken_for_roles.yaml

* Change ID token for role to use API Gateway proxy mode and pass all requests onto the Lambda function
* Change how ID token for role decides what action to take. Previously it used the HTTP method. Now it uses the URL path
* Add new Group Role Map rebuild triggering mechanism
* Add new AllowedMapBuilderSubPrefix setting to limit who can trigger map rebuilds
* Limit concurrent executions of the group role map builder to prevent multiple simultaneous builds
* Export the group role map builder lambda function name and ARN to CloudFormation for consumption by the ID token for role API
* Add new functionality to ID token for role allowing an authenticated user with a sub beginning with the ALLOWED_MAP_BUILDER_SUB_PREFIX to trigger a group role map rebuild
* Grant the ID token for role API …

Add new Group Role Map rebuild triggering mechanism

---

CHANGELOG.md
mozilla_aws_cli/login.py
setup.py

* Change format of idtoken_for_roles_url
* This changes the expectation of a configured idtoken_for_roles_url from
https://example.com/roles
* to
https://example.com/
* Remove no longer used console-menu requirement

Update for v0.2.0

---

mozilla_aws_cli/cli.py
mozilla_aws_cli/listener.py
mozilla_aws_cli/login.py
mozilla_aws_cli/role_picker.py
mozilla_aws_cli/sts_conn.py
mozilla_aws_cli/utils.py

Fix handling STS AccessDenied responses
* Consolidate the STSWarning class in utils because otherwise each module's STSWarning is a distinct class
* Change login.exchange_token_for_credentials so it no longer loops, retrying t get credentials.
* This looping has been moved up to listener.py where we want to loop (when we have a role picker)
* Fix when a role is passed as a CLI argument but AWS responds with AccessDenied
* Now, if this happens, the CLI spawns the role picker to select a different role
* Unless --batch is specified in which case the CLI just exits
Update cached role_map if AWS gives AccessDenied
AWS returning AccessDenied is a good indicator that our cached role map isn't accurate.
This makes the tool refresh the role map if an AccessDenied is encountered
This also …

Fix handling STS AccessDenied responses

---

README.md
mozilla_aws_cli/cli.py
mozilla_aws_cli/listener.py
mozilla_aws_cli/login.py
mozilla_aws_cli/static/index.js

* Removed synchronous blocking frontend backend interactions and instead this now relies entirely on the pollState frontend polling loop
* Previously there was a mix of frontend backend interactions which were async and one which blocked and waited for other async calls to finish
* This previous blocking interaction was when the frontend called "/redirect_callback". handle_oidc_redirect_callback
would then call login.exchange_token_for_credentials which would loop and wait for a separate POST from the frontend to /api/roles to
complete before login.exchange_token_for_credentials would continue and allow /redirect_callback to return a response to the frontend.
* This commit removes this behavior so that all frontend to backend interactions are async and the frontends movement through the …

Remove synchronous blocking frontend backend interactions

---

cloudformation/Makefile
mozilla_aws_cli/login.py
mozilla_aws_cli/role_picker.py

This changes how the environment variables that maws outputs are conveyed to the parent shell.
Previously a single command was emitted (for non Windows clients) in the form of
"export foo=bar baz=buz"
This is limited to a single command because of how this output is being interpreted by the $(maws)
subshell wrapper.
To work around this limitation maws now produces a temporary shell script which is "sourced" into
the parent shell. This way an arbitrary number of commands can be injected into the parent shell
The temporary shell script
* exports environment variables
* unsets environment variables that should no longer be set
* provisions a function that outputs the current profile name
* modifies the $PS1 prompt to call this function
* deletes itself
This accomplishes two things
* Ensures …

Change from outputting export to rendering shell script and add shell prompt info

---

CHANGELOG.md
mozilla_aws_cli/login.py

Changed the issuer URL which is used when an AWS web console session expires to enable the
user to refresh their session by visiting the federated-aws-rp. Previously the
URL shown to the user contained the AWS account ID. Now it contains the more
human readable account alias.
Fixes #186

Changed issuer URL to contain AWS account alias

---

CHANGELOG.md
mozilla_aws_cli/login.py
setup.py

Revert the change in #160 in which the URL format for idtoken_for_roles_url
was changed from https://example.com/roles to https://example.com/.
Now with this reversion, the idtoken_for_roles_url should again be the full
URL ending in `/roles`. This change is not backwards compatible and will
require that a config file or config module be changed to use the new full URL.
Fixes #182

Change idtoken_for_roles_url format to https://example.com/roles

---

cloudformation/Makefile
mozilla_aws_cli/cache.py
mozilla_aws_cli/login.py

* Add make target to create a test federated IAM role
* Fix STSWarning handling when the exception doesn't come from boto
* Update safe cache dir check to ensure dir exists as well
Fixes #198

Create parent directories for cache and config dirs

---

mozilla_aws_cli/role_picker.py
mozilla_aws_cli/static/index.js

Fix broken error display and errors where AWS puts `error` into `message` instead. This usually happens when your URL is missing `/roles`.

Fix a pair of error handling bugs

---

mozilla_aws_cli/cli.py
mozilla_aws_cli/login.py
mozilla_aws_cli/utils.py

* Change prompt to always use role name, never profile name
* Stop overloading `profile_name` and use previously unused `self.role`
* Change function name to indicate actual function
* Fix slightly unrelated bug with using `-o awscli` or `-o shared` without a profile name
Fixes #215.

Fixes related to maws prompt

---

cloudformation/group_role_map_builder/functions/group_role_map_builder.py
cloudformation/group_role_map_builder/group_role_map_builder.yaml
cloudformation/group_role_map_builder/tests/policies/wrong_principal_aws_account_id.json
cloudformation/group_role_map_builder/tests/test_compare_group_arn_maps.py
cloudformation/group_role_map_builder/tests/test_get_groups_from_policy.py
cloudformation/idtoken_for_roles/functions/idtoken_for_roles.py
cloudformation/idtoken_for_roles/idtoken_for_roles.yaml
cloudformation/tox.ini
mozilla_aws_cli/cache.py
mozilla_aws_cli/listener.py
mozilla_aws_cli/login.py
tox.ini

* Add a check that the federated principal in an IAM policy has the same AWS account ID as the account containing the policy.
* Also switch from character offset based checks to delimiter split checks
* Add debug log line for matching groups
* Adding this check as I encountered an invalid policy today that was allowed by maws and rejected by AWS
* Update Lambda functions to Python 3.8

Add check that policy principal account ID is correct

---

cloudformation/idtoken_for_roles/functions/idtoken_for_roles.py
mozilla_aws_cli/listener.py
mozilla_aws_cli/login.py
mozilla_aws_cli/utils.py

Previously, if a user used mozilla-aws-cli with an AWS account that had no account alias
defined, it would respond with errors described in #220 like
```
File "/path/to/mozilla_aws_cli/listener.py", line 92, in get_roles
alias = login.role_map.get(
IndexError: list index out of range
```
and
```
File "/path/to/mozilla_aws_cli/utils.py", line 44, in role_arn_to_display_name
account_id = role_map.get("aliases", {}).get(account_id, [account_id])[0]
IndexError: list index out of range
```
This commit both changes the ID Token For Roles API to stop returning entries in alias maps with no aliases and updates mozilla-aws-cli to gracefully deal with cases where the ID Token For Roles API returns an empty alias list.
Fixes #220

Fix bug when AWS Account has no alias

---

mozilla_aws_cli/cache.py
mozilla_aws_cli/cli.py
setup.py

Fix output awscli on Windows

---

setup.py

This PR updates `setup.py` to include the [canonical](https://pypi.org/classifiers/) classifier for the MPL 2.0 license of this repository.

Add MPL 2.0 classifier to setup.py

---

CHANGELOG.md
mozilla_aws_cli/static/index.html
setup.py

I am often confused searching the login page for the AWS Account ID that corresponds to the Role I want to select. This simply add the Account ID to the output for faster finding. Open to suggestions or feedback if folks have other workflows that solve this.
*Note* These are not the real account numbers.

Add account id to account name

---

CHANGELOG.md
setup.py

This fixes a conflict with Werkzeug version 2.1.0 and newer which caused a
`KeyError: 'WERKZEUG_SERVER_FD'`.
This fix limits the max version of Werkzeug. A more permanent fix will be to
move away from using the Flask development server to another WSGI listener.
Fixes #243
Also
* Update classifier to show support up to Python 3.9
* Limit versions of dependent packages to retain python 2.7 support

Fixes KeyError: 'WERKZEUG_SERVER_FD' error

---

cloudformation/group_role_map_builder/functions/group_role_map_builder.py
cloudformation/group_role_map_builder/tests/test_compare_group_arn_maps.py

As we no longer use MozDef, and support for MozDef was never actually enabled in the Group Role Map builder, this removes support for it.
Also
* Clean up logging
* This switches string formatting method, changes an ERROR log to DEBUG and adds account ID information to some log lines
* Fix typing for serialize_map since it returns UTF-8 encoded bytes, not a string

Remove MozDef support
