federated_boto/login.py

Add logging

---

federated_aws_cli/login.py

cleanups ported from https://github.com/mozilla-iam/federated-mercurial/

---

tests/auth0.py
tests/test_federated_boto.py
tests/test_sts_conn.py
tox.ini

Fix flake8

---

tests/test_federated_boto.py

Remove unneeded test invocation

---

.travis.yml
cloudformation/functions/get_group_role_map.py
cloudformation/functions/tests/test_get_group_role_map.py
cloudformation/tox.ini
tox.ini

Break out tox testing of cli and lambda functions into two jobs

---

federated_aws_cli/login.py

... and also your default browser. The current code will only gracefully open in a new tab if you're using firefox release. It's really bad if you use Firefox Nightly, as I do.

Tell webbrowser to use new tab

---

federated_aws_cli/cli.py

Check /etc/federated_aws_cli.yaml for settings first, and then overlay them with the ones set in your home directory. This allows sysadmins (etc.) to have a file they can deploy into /etc.

Update CLI to check etc first

---

federated_aws_cli/cli.py
tests/test_federated_aws_cli.py

Also clean up the Py2/Py3 detection.

Fix test errors

---

setup.py

Include static assets in python package

---

federated_aws_cli/cache.py
federated_aws_cli/role_picker.py

Plus a lot of code changes to fix permissions and avoid code duplication.

Add caching for group role map

---

federated_aws_cli/cache.py
federated_aws_cli/cli.py
federated_aws_cli/login.py
federated_aws_cli/role_picker.py

Add support for the AWS CLI.

---

federated_aws_cli/cache.py
federated_aws_cli/cli.py
federated_aws_cli/listener.py
federated_aws_cli/login.py
federated_aws_cli/static/index.html
federated_aws_cli/static/index.js
federated_aws_cli/utils.py

• Can now disable the reading of locally cached files, which is helpful for debugging
• The new tab now maintains the status of things, and once federation is done it will tell if you if it is redirecting to AWS or that you can close the window
• No second tab for opening the AWS web console
• A bunch of bug fixes and style consistency

Much better web console experience, option to disable cache

---

federated_aws_cli/cache.py
federated_aws_cli/login.py
federated_aws_cli/role_picker.py
setup.py

With this update to the output the user can eval the output and have a working session
Also Minor fixes for setup.py

Update the shared credential output to include profile

---

federated_aws_cli/cache.py

Previously we were comparing local time to UTC time and so the comparison was always off. This change compares UTC to UTC time and works in python 2 and 3

Fix sts session expiry comparison

---

federated_aws_cli/login.py

Particularly not exiting if using `-w` with cached files.

Minor code cleanup and bug fixes

---

federated_aws_cli/cli.py

See mozilla-iam/federated-aws-rp#6

Change issue to deployment in the mozilla-iam AWS account

---

cloudformation/deploy.sh
cloudformation/idtoken_for_roles/functions/idtoken_for_roles.py

* make logging log level variable
* Fix incorrect S3 bucket used for Lambda code storage
* Test that we have a usable AWS connection when deploying
* Show stack events if there's a failure
Related PR mozilla-iam/federated-aws-rp#9

Allow passing a cache parameter to idtoken_for_roles to disable cache

---

CHANGELOG.md
setup.py

Open up the dependent package versions to accept newer versions
Add a changelog

Release v0.0.2

---

README.md
mozilla_aws_cli/login.py
mozilla_aws_cli/role_picker.py

This removes carriage returns from the output so that the result is
a single line command that sets up the environment
Also add documentation around this

Add support for $(maws) syntax

---

CHANGELOG.md
mozilla_aws_cli/cli.py
setup.py

Fix missing support for Python 2 and the config module

---

README.md

Add warning about YADR and zsh.

---

mozilla_aws_cli/listener.py
mozilla_aws_cli/login.py

Check if the web interface is still running and shut down if not

---

mozilla_aws_cli/login.py

Error out when specifying role with -r that's not available.

---

mozilla_aws_cli/cli.py
mozilla_aws_cli/login.py
mozilla_aws_cli/role_picker.py

to force it to use or not use cache

Pass the cache state on to the idtoken for role API

---

mozilla_aws_cli/cache.py

This causes permissions on config and cache directories to be fixed if they're wrong
(instead of just being detected but not fixed)
Fixes #96

Enable correcting directory permissions

---

mozilla_aws_cli/cli.py
mozilla_aws_cli/listener.py
mozilla_aws_cli/login.py
mozilla_aws_cli/role_picker.py

Add error checking for network failures

---

mozilla_aws_cli/cache.py
mozilla_aws_cli/cli.py
mozilla_aws_cli/config.py
mozilla_aws_cli/login.py
mozilla_aws_cli/static/index.js
mozilla_aws_cli/sts_conn.py

Fixes #169, #168, #167, and #161.

Fix the various Windows errors

---

setup.py

Require future.utils.

---

README.md
mozilla_aws_cli/cache.py
mozilla_aws_cli/cli.py
mozilla_aws_cli/config.py
mozilla_aws_cli/listener.py
mozilla_aws_cli/login.py
mozilla_aws_cli/static/index.html
mozilla_aws_cli/static/index.js
setup.py

By using `appdirs`, for the most part.

Switch to XDG specification

---

.jshintrc
mozilla_aws_cli/cache.py
mozilla_aws_cli/cli.py
mozilla_aws_cli/listener.py
mozilla_aws_cli/login.py
mozilla_aws_cli/role_picker.py
mozilla_aws_cli/static/index.js
mozilla_aws_cli/sts_conn.py
mozilla_aws_cli/utils.py

* Improve style and conform to PEP008
* Remove leftover unused return
* Clarify how the AWS XML response is parsed : Fixes #23
* Improve JS style
* Removing unused sleep variable
* Add jshintrc

Fixup style

---

CHANGELOG.md
setup.py

Add links to CHANGELOG issue and PR references
This should put us in a position to cut a new release

Update CHANGELOG and setup.py to v1.0.0

---

.travis.yml
CHANGELOG.md

Also, try fixing Travis pypi deploy process

Update CHANGELOG with last minute 1.0.0 addition

---

mozilla_aws_cli/login.py
mozilla_aws_cli/role_picker.py
mozilla_aws_cli/sts_conn.py

Add credential expiry check to command line prompt

---

mozilla_aws_cli/listener.py

Remove debug logging for /api/state and /api/hearbeat

---

CHANGELOG.md
setup.py

Release 1.1.1

---

mozilla_aws_cli/role_picker.py

Fix detection of maws_profile in PS1 in zsh

---

mozilla_aws_cli/cli.py
mozilla_aws_cli/login.py

Add --print-url. Fixes #205.

---

mozilla_aws_cli/static/index.js

Also send the send the alias and role values so the frontend for maws and federated-aws-rp match
This matches up with mozilla-iam/federated-aws-rp#25

Add support for info state

---

README.md
cloudformation/README.md
cloudformation/group_role_map_builder/README.md
cloudformation/idtoken_for_roles/README.md
docs/README.md

Add documentation for ID Token for Roles and Group Role Map Builder and improve the README

Improve the documentation

---

.travis.yml
CHANGELOG.md
mozilla_aws_cli/cli.py
setup.py

Also
* Limit package rsa to version 4.5 under python 2.7 as support was dropped after this version
* Fix flake8 errors from #235 related to a bare except

Update to v1.2.3
